// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/payload_api.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
namespace Chorus.WindowsReader.Common
{

    /// <summary>Holder for reflection information generated from Proto/payload_api.proto</summary>
    public static partial class PayloadApiReflection
    {

        #region Descriptor
        /// <summary>File descriptor for Proto/payload_api.proto</summary>
        public static pbr::FileDescriptor Descriptor
        {
            get { return descriptor; }
        }
        private static pbr::FileDescriptor descriptor;

        static PayloadApiReflection()
        {
            byte[] descriptorData = global::System.Convert.FromBase64String(
                string.Concat(
                  "ChdQcm90by9wYXlsb2FkX2FwaS5wcm90bxIVZ29vZ2xlLnNjb3V0LnYxYWxw",
                  "aGExGh9nb29nbGUvcHJvdG9idWYvdGltZXN0YW1wLnByb3RvGhRwcm90by9s",
                  "b2NhdGlvbi5wcm90byLiBAoHUGF5bG9hZBIRCglkZXZpY2VfaWQYASABKAkS",
                  "DgoGb3JnX2lkGAIgASgJEj8KD2RldmljZV9sb2NhdGlvbhgDIAEoCzImLmdv",
                  "b2dsZS5zY291dC52MWFscGhhMS5EZXJpdmVkTG9jYXRpb24SOAoUZGV2aWNl",
                  "X2xvY2F0aW9uX3RpbWUYBSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0",
                  "YW1wEkUKD2JlYWNvbl9wYXlsb2FkcxgEIAMoCzIsLmdvb2dsZS5zY291dC52",
                  "MWFscGhhMS5QYXlsb2FkLkJlYWNvblBheWxvYWQSQAoIbWV0YWRhdGEYBiAB",
                  "KAsyLi5nb29nbGUuc2NvdXQudjFhbHBoYTEuUGF5bG9hZC5QYXlsb2FkTWV0",
                  "YWRhdGEaeAoNQmVhY29uUGF5bG9hZBIdChVibGVfbWFudWZhY3R1cmVyX2Rh",
                  "dGEYASABKAwSMAoMcmVjZWl2ZV90aW1lGAIgASgLMhouZ29vZ2xlLnByb3Rv",
                  "YnVmLlRpbWVzdGFtcBIQCghyc3NpX2RibRgDIAEoEUoECAQQBRq1AQoPUGF5",
                  "bG9hZE1ldGFkYXRhEkcKBHR5cGUYASABKA4yOS5nb29nbGUuc2NvdXQudjFh",
                  "bHBoYTEuUGF5bG9hZC5QYXlsb2FkTWV0YWRhdGEuRGV2aWNlVHlwZRIPCgd2",
                  "ZXJzaW9uGAIgASgJIkgKCkRldmljZVR5cGUSFwoTVU5LTk9XTl9ERVZJQ0Vf",
                  "VFlQRRAAEgsKB0FORFJPSUQQARIHCgNJT1MQAhILCgdXSU5ET1dTEANCTQoZ",
                  "Y29tLmdvb2dsZS5zY291dC52MWFscGhhMVABWi5zb3VyY2UuY2xvdWQuZ29v",
                  "Z2xlLmNvbS9jaG9ydXMtc2NvdXQvYXBpLXByb3RvYgZwcm90bzM="));
            descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
                new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Chorus.WindowsReader.Common.LocationReflection.Descriptor, },
                new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Chorus.WindowsReader.Common.Payload), global::Chorus.WindowsReader.Common.Payload.Parser, new[]{ "DeviceId", "OrgId", "DeviceLocation", "DeviceLocationTime", "BeaconPayloads", "Metadata" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Chorus.WindowsReader.Common.Payload.Types.BeaconPayload), global::Chorus.WindowsReader.Common.Payload.Types.BeaconPayload.Parser, new[]{ "BleManufacturerData", "ReceiveTime", "RssiDbm" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chorus.WindowsReader.Common.Payload.Types.PayloadMetadata), global::Chorus.WindowsReader.Common.Payload.Types.PayloadMetadata.Parser, new[]{ "Type", "Version" }, null, new[]{ typeof(global::Chorus.WindowsReader.Common.Payload.Types.PayloadMetadata.Types.DeviceType) }, null, null)})
                }));
        }
        #endregion

    }
    #region Messages
    [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
    public sealed partial class Payload : pb::IMessage<Payload>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<Payload> _parser = new pb::MessageParser<Payload>(() => new Payload());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Payload> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Chorus.WindowsReader.Common.PayloadApiReflection.Descriptor.MessageTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Payload()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Payload(Payload other) : this()
        {
            deviceId_ = other.deviceId_;
            orgId_ = other.orgId_;
            deviceLocation_ = other.deviceLocation_ != null ? other.deviceLocation_.Clone() : null;
            deviceLocationTime_ = other.deviceLocationTime_ != null ? other.deviceLocationTime_.Clone() : null;
            beaconPayloads_ = other.beaconPayloads_.Clone();
            metadata_ = other.metadata_ != null ? other.metadata_.Clone() : null;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Payload Clone()
        {
            return new Payload(this);
        }

        /// <summary>Field number for the "device_id" field.</summary>
        public const int DeviceIdFieldNumber = 1;
        private string deviceId_ = "";
        /// <summary>
        /// The ID of the device that "saw" the beacon_payloads. This ID is treated
        /// opaquely by the Chorus system but can be used to uniquely identify the
        /// device, if desired. Must be a valid UTF-8 string.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string DeviceId
        {
            get { return deviceId_; }
            set
            {
                deviceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "org_id" field.</summary>
        public const int OrgIdFieldNumber = 2;
        private string orgId_ = "";
        /// <summary>
        /// ID provided to you by the Chorus team to identify your organization. For
        /// example, 'cb31'
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string OrgId
        {
            get { return orgId_; }
            set
            {
                orgId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "device_location" field.</summary>
        public const int DeviceLocationFieldNumber = 3;
        private global::Chorus.WindowsReader.Common.DerivedLocation deviceLocation_;
        /// <summary>
        /// The location of the device that "saw" the beacon_payloads. This location
        /// will temporarily be applied to all beacon_payloads below, regardless of
        /// the receive_time. We intend to make this more granular in the future.
        ///
        /// Do not set the "source" field; its value is disregarded and always set to
        /// GNSS/GPS.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Chorus.WindowsReader.Common.DerivedLocation DeviceLocation
        {
            get { return deviceLocation_; }
            set
            {
                deviceLocation_ = value;
            }
        }

        /// <summary>Field number for the "device_location_time" field.</summary>
        public const int DeviceLocationTimeFieldNumber = 5;
        private global::Google.Protobuf.WellKnownTypes.Timestamp deviceLocationTime_;
        /// <summary>
        /// The time at which the location was collected by the device
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Google.Protobuf.WellKnownTypes.Timestamp DeviceLocationTime
        {
            get { return deviceLocationTime_; }
            set
            {
                deviceLocationTime_ = value;
            }
        }

        /// <summary>Field number for the "beacon_payloads" field.</summary>
        public const int BeaconPayloadsFieldNumber = 4;
        private static readonly pb::FieldCodec<global::Chorus.WindowsReader.Common.Payload.Types.BeaconPayload> _repeated_beaconPayloads_codec
            = pb::FieldCodec.ForMessage(34, global::Chorus.WindowsReader.Common.Payload.Types.BeaconPayload.Parser);
        private readonly pbc::RepeatedField<global::Chorus.WindowsReader.Common.Payload.Types.BeaconPayload> beaconPayloads_ = new pbc::RepeatedField<global::Chorus.WindowsReader.Common.Payload.Types.BeaconPayload>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<global::Chorus.WindowsReader.Common.Payload.Types.BeaconPayload> BeaconPayloads
        {
            get { return beaconPayloads_; }
        }

        /// <summary>Field number for the "metadata" field.</summary>
        public const int MetadataFieldNumber = 6;
        private global::Chorus.WindowsReader.Common.Payload.Types.PayloadMetadata metadata_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Chorus.WindowsReader.Common.Payload.Types.PayloadMetadata Metadata
        {
            get { return metadata_; }
            set
            {
                metadata_ = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as Payload);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Payload other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (DeviceId != other.DeviceId) return false;
            if (OrgId != other.OrgId) return false;
            if (!object.Equals(DeviceLocation, other.DeviceLocation)) return false;
            if (!object.Equals(DeviceLocationTime, other.DeviceLocationTime)) return false;
            if (!beaconPayloads_.Equals(other.beaconPayloads_)) return false;
            if (!object.Equals(Metadata, other.Metadata)) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (DeviceId.Length != 0) hash ^= DeviceId.GetHashCode();
            if (OrgId.Length != 0) hash ^= OrgId.GetHashCode();
            if (deviceLocation_ != null) hash ^= DeviceLocation.GetHashCode();
            if (deviceLocationTime_ != null) hash ^= DeviceLocationTime.GetHashCode();
            hash ^= beaconPayloads_.GetHashCode();
            if (metadata_ != null) hash ^= Metadata.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (DeviceId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DeviceId);
      }
      if (OrgId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(OrgId);
      }
      if (deviceLocation_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(DeviceLocation);
      }
      beaconPayloads_.WriteTo(output, _repeated_beaconPayloads_codec);
      if (deviceLocationTime_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(DeviceLocationTime);
      }
      if (metadata_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Metadata);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (DeviceId.Length != 0)
            {
                output.WriteRawTag(10);
                output.WriteString(DeviceId);
            }
            if (OrgId.Length != 0)
            {
                output.WriteRawTag(18);
                output.WriteString(OrgId);
            }
            if (deviceLocation_ != null)
            {
                output.WriteRawTag(26);
                output.WriteMessage(DeviceLocation);
            }
            beaconPayloads_.WriteTo(ref output, _repeated_beaconPayloads_codec);
            if (deviceLocationTime_ != null)
            {
                output.WriteRawTag(42);
                output.WriteMessage(DeviceLocationTime);
            }
            if (metadata_ != null)
            {
                output.WriteRawTag(50);
                output.WriteMessage(Metadata);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (DeviceId.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceId);
            }
            if (OrgId.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(OrgId);
            }
            if (deviceLocation_ != null)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(DeviceLocation);
            }
            if (deviceLocationTime_ != null)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(DeviceLocationTime);
            }
            size += beaconPayloads_.CalculateSize(_repeated_beaconPayloads_codec);
            if (metadata_ != null)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(Metadata);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Payload other)
        {
            if (other == null)
            {
                return;
            }
            if (other.DeviceId.Length != 0)
            {
                DeviceId = other.DeviceId;
            }
            if (other.OrgId.Length != 0)
            {
                OrgId = other.OrgId;
            }
            if (other.deviceLocation_ != null)
            {
                if (deviceLocation_ == null)
                {
                    DeviceLocation = new global::Chorus.WindowsReader.Common.DerivedLocation();
                }
                DeviceLocation.MergeFrom(other.DeviceLocation);
            }
            if (other.deviceLocationTime_ != null)
            {
                if (deviceLocationTime_ == null)
                {
                    DeviceLocationTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
                }
                DeviceLocationTime.MergeFrom(other.DeviceLocationTime);
            }
            beaconPayloads_.Add(other.beaconPayloads_);
            if (other.metadata_ != null)
            {
                if (metadata_ == null)
                {
                    Metadata = new global::Chorus.WindowsReader.Common.Payload.Types.PayloadMetadata();
                }
                Metadata.MergeFrom(other.Metadata);
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            DeviceId = input.ReadString();
            break;
          }
          case 18: {
            OrgId = input.ReadString();
            break;
          }
          case 26: {
            if (deviceLocation_ == null) {
              DeviceLocation = new global::Chorus.WindowsReader.Common.DerivedLocation();
            }
            input.ReadMessage(DeviceLocation);
            break;
          }
          case 34: {
            beaconPayloads_.AddEntriesFrom(input, _repeated_beaconPayloads_codec);
            break;
          }
          case 42: {
            if (deviceLocationTime_ == null) {
              DeviceLocationTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DeviceLocationTime);
            break;
          }
          case 50: {
            if (metadata_ == null) {
              Metadata = new global::Chorus.WindowsReader.Common.Payload.Types.PayloadMetadata();
            }
            input.ReadMessage(Metadata);
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 10:
                        {
                            DeviceId = input.ReadString();
                            break;
                        }
                    case 18:
                        {
                            OrgId = input.ReadString();
                            break;
                        }
                    case 26:
                        {
                            if (deviceLocation_ == null)
                            {
                                DeviceLocation = new global::Chorus.WindowsReader.Common.DerivedLocation();
                            }
                            input.ReadMessage(DeviceLocation);
                            break;
                        }
                    case 34:
                        {
                            beaconPayloads_.AddEntriesFrom(ref input, _repeated_beaconPayloads_codec);
                            break;
                        }
                    case 42:
                        {
                            if (deviceLocationTime_ == null)
                            {
                                DeviceLocationTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
                            }
                            input.ReadMessage(DeviceLocationTime);
                            break;
                        }
                    case 50:
                        {
                            if (metadata_ == null)
                            {
                                Metadata = new global::Chorus.WindowsReader.Common.Payload.Types.PayloadMetadata();
                            }
                            input.ReadMessage(Metadata);
                            break;
                        }
                }
            }
        }
#endif

        #region Nested types
        /// <summary>Container for nested types declared in the Payload message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types
        {
            [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
            public sealed partial class BeaconPayload : pb::IMessage<BeaconPayload>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                , pb::IBufferMessage
#endif
            {
                private static readonly pb::MessageParser<BeaconPayload> _parser = new pb::MessageParser<BeaconPayload>(() => new BeaconPayload());
                private pb::UnknownFieldSet _unknownFields;
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public static pb::MessageParser<BeaconPayload> Parser { get { return _parser; } }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public static pbr::MessageDescriptor Descriptor
                {
                    get { return global::Chorus.WindowsReader.Common.Payload.Descriptor.NestedTypes[0]; }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                pbr::MessageDescriptor pb::IMessage.Descriptor
                {
                    get { return Descriptor; }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public BeaconPayload()
                {
                    OnConstruction();
                }

                partial void OnConstruction();

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public BeaconPayload(BeaconPayload other) : this()
                {
                    bleManufacturerData_ = other.bleManufacturerData_;
                    receiveTime_ = other.receiveTime_ != null ? other.receiveTime_.Clone() : null;
                    rssiDbm_ = other.rssiDbm_;
                    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public BeaconPayload Clone()
                {
                    return new BeaconPayload(this);
                }

                /// <summary>Field number for the "ble_manufacturer_data" field.</summary>
                public const int BleManufacturerDataFieldNumber = 1;
                private pb::ByteString bleManufacturerData_ = pb::ByteString.Empty;
                /// <summary>
                /// Raw bytes of the full manufacturer-specific data in the BLE data packet
                /// advertised by the device. Manufacturer-specific data is indicated by the
                /// advertising data (AD) type 0xFF, per [1].
                ///
                /// This field should be populated with only the manufacturer-specific data,
                /// starting from and including the Customer Identifier Code (CIC), as
                /// documented in [2]. Do not include the aforementioned AD type byte (0xFF),
                /// which immediately precedes the CIC, or the associated length byte that
                /// precedes the AD type.
                ///
                /// Furthermore, do not include any BLE advertisement flags or any data from
                /// the scan response (if there is one).
                ///
                /// For example, given the following raw advertisement data packet (in hex):
                ///     0x02010417FFE00013190112FC5394C37CAC364210CDC758883EC1E8
                /// This field should comprise the following bytes (presented here in hex):
                ///     0xE00013190112FC5394C37CAC364210CDC758883EC1E8
                ///
                /// In the above example, 0x020104 is a flags AD element (per [1]), and the
                /// remainder of the advertisement packet (starting with 0x17) is a
                /// "manufacturer-specific" AD element. We are interested only in the actual
                /// data in the latter AD element, so we expect everything starting from the
                /// 0xE0 byte but *not* the 0x17 byte (length) or the 0xFF byte (AD type).
                ///
                /// [1] https://www.bluetooth.com/specifications/assigned-numbers/generic-access-profile/
                /// [2] https://www.bluetooth.com/specifications/assigned-numbers/company-identifiers/
                /// </summary>
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public pb::ByteString BleManufacturerData
                {
                    get { return bleManufacturerData_; }
                    set
                    {
                        bleManufacturerData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
                    }
                }

                /// <summary>Field number for the "receive_time" field.</summary>
                public const int ReceiveTimeFieldNumber = 2;
                private global::Google.Protobuf.WellKnownTypes.Timestamp receiveTime_;
                /// <summary>
                /// Time the payload was received.
                /// </summary>
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public global::Google.Protobuf.WellKnownTypes.Timestamp ReceiveTime
                {
                    get { return receiveTime_; }
                    set
                    {
                        receiveTime_ = value;
                    }
                }

                /// <summary>Field number for the "rssi_dbm" field.</summary>
                public const int RssiDbmFieldNumber = 3;
                private int rssiDbm_;
                /// <summary>
                /// Received signal strength, in dBm.
                /// </summary>
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public int RssiDbm
                {
                    get { return rssiDbm_; }
                    set
                    {
                        rssiDbm_ = value;
                    }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public override bool Equals(object other)
                {
                    return Equals(other as BeaconPayload);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public bool Equals(BeaconPayload other)
                {
                    if (ReferenceEquals(other, null))
                    {
                        return false;
                    }
                    if (ReferenceEquals(other, this))
                    {
                        return true;
                    }
                    if (BleManufacturerData != other.BleManufacturerData) return false;
                    if (!object.Equals(ReceiveTime, other.ReceiveTime)) return false;
                    if (RssiDbm != other.RssiDbm) return false;
                    return Equals(_unknownFields, other._unknownFields);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public override int GetHashCode()
                {
                    int hash = 1;
                    if (BleManufacturerData.Length != 0) hash ^= BleManufacturerData.GetHashCode();
                    if (receiveTime_ != null) hash ^= ReceiveTime.GetHashCode();
                    if (RssiDbm != 0) hash ^= RssiDbm.GetHashCode();
                    if (_unknownFields != null)
                    {
                        hash ^= _unknownFields.GetHashCode();
                    }
                    return hash;
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public override string ToString()
                {
                    return pb::JsonFormatter.ToDiagnosticString(this);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public void WriteTo(pb::CodedOutputStream output)
                {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                    output.WriteRawMessage(this);
#else
          if (BleManufacturerData.Length != 0) {
            output.WriteRawTag(10);
            output.WriteBytes(BleManufacturerData);
          }
          if (receiveTime_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(ReceiveTime);
          }
          if (RssiDbm != 0) {
            output.WriteRawTag(24);
            output.WriteSInt32(RssiDbm);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
#endif
                }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
                {
                    if (BleManufacturerData.Length != 0)
                    {
                        output.WriteRawTag(10);
                        output.WriteBytes(BleManufacturerData);
                    }
                    if (receiveTime_ != null)
                    {
                        output.WriteRawTag(18);
                        output.WriteMessage(ReceiveTime);
                    }
                    if (RssiDbm != 0)
                    {
                        output.WriteRawTag(24);
                        output.WriteSInt32(RssiDbm);
                    }
                    if (_unknownFields != null)
                    {
                        _unknownFields.WriteTo(ref output);
                    }
                }
#endif

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public int CalculateSize()
                {
                    int size = 0;
                    if (BleManufacturerData.Length != 0)
                    {
                        size += 1 + pb::CodedOutputStream.ComputeBytesSize(BleManufacturerData);
                    }
                    if (receiveTime_ != null)
                    {
                        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ReceiveTime);
                    }
                    if (RssiDbm != 0)
                    {
                        size += 1 + pb::CodedOutputStream.ComputeSInt32Size(RssiDbm);
                    }
                    if (_unknownFields != null)
                    {
                        size += _unknownFields.CalculateSize();
                    }
                    return size;
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public void MergeFrom(BeaconPayload other)
                {
                    if (other == null)
                    {
                        return;
                    }
                    if (other.BleManufacturerData.Length != 0)
                    {
                        BleManufacturerData = other.BleManufacturerData;
                    }
                    if (other.receiveTime_ != null)
                    {
                        if (receiveTime_ == null)
                        {
                            ReceiveTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
                        }
                        ReceiveTime.MergeFrom(other.ReceiveTime);
                    }
                    if (other.RssiDbm != 0)
                    {
                        RssiDbm = other.RssiDbm;
                    }
                    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public void MergeFrom(pb::CodedInputStream input)
                {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                    input.ReadRawMessage(this);
#else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                BleManufacturerData = input.ReadBytes();
                break;
              }
              case 18: {
                if (receiveTime_ == null) {
                  ReceiveTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
                }
                input.ReadMessage(ReceiveTime);
                break;
              }
              case 24: {
                RssiDbm = input.ReadSInt32();
                break;
              }
            }
          }
#endif
                }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
                {
                    uint tag;
                    while ((tag = input.ReadTag()) != 0)
                    {
                        switch (tag)
                        {
                            default:
                                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                                break;
                            case 10:
                                {
                                    BleManufacturerData = input.ReadBytes();
                                    break;
                                }
                            case 18:
                                {
                                    if (receiveTime_ == null)
                                    {
                                        ReceiveTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
                                    }
                                    input.ReadMessage(ReceiveTime);
                                    break;
                                }
                            case 24:
                                {
                                    RssiDbm = input.ReadSInt32();
                                    break;
                                }
                        }
                    }
                }
#endif

            }

            [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
            public sealed partial class PayloadMetadata : pb::IMessage<PayloadMetadata>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                , pb::IBufferMessage
#endif
            {
                private static readonly pb::MessageParser<PayloadMetadata> _parser = new pb::MessageParser<PayloadMetadata>(() => new PayloadMetadata());
                private pb::UnknownFieldSet _unknownFields;
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public static pb::MessageParser<PayloadMetadata> Parser { get { return _parser; } }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public static pbr::MessageDescriptor Descriptor
                {
                    get { return global::Chorus.WindowsReader.Common.Payload.Descriptor.NestedTypes[1]; }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                pbr::MessageDescriptor pb::IMessage.Descriptor
                {
                    get { return Descriptor; }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public PayloadMetadata()
                {
                    OnConstruction();
                }

                partial void OnConstruction();

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public PayloadMetadata(PayloadMetadata other) : this()
                {
                    type_ = other.type_;
                    version_ = other.version_;
                    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public PayloadMetadata Clone()
                {
                    return new PayloadMetadata(this);
                }

                /// <summary>Field number for the "type" field.</summary>
                public const int TypeFieldNumber = 1;
                private global::Chorus.WindowsReader.Common.Payload.Types.PayloadMetadata.Types.DeviceType type_ = global::Chorus.WindowsReader.Common.Payload.Types.PayloadMetadata.Types.DeviceType.UnknownDeviceType;
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public global::Chorus.WindowsReader.Common.Payload.Types.PayloadMetadata.Types.DeviceType Type
                {
                    get { return type_; }
                    set
                    {
                        type_ = value;
                    }
                }

                /// <summary>Field number for the "version" field.</summary>
                public const int VersionFieldNumber = 2;
                private string version_ = "";
                /// <summary>
                /// The version identifier of the software that sent the payload
                /// </summary>
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public string Version
                {
                    get { return version_; }
                    set
                    {
                        version_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
                    }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public override bool Equals(object other)
                {
                    return Equals(other as PayloadMetadata);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public bool Equals(PayloadMetadata other)
                {
                    if (ReferenceEquals(other, null))
                    {
                        return false;
                    }
                    if (ReferenceEquals(other, this))
                    {
                        return true;
                    }
                    if (Type != other.Type) return false;
                    if (Version != other.Version) return false;
                    return Equals(_unknownFields, other._unknownFields);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public override int GetHashCode()
                {
                    int hash = 1;
                    if (Type != global::Chorus.WindowsReader.Common.Payload.Types.PayloadMetadata.Types.DeviceType.UnknownDeviceType) hash ^= Type.GetHashCode();
                    if (Version.Length != 0) hash ^= Version.GetHashCode();
                    if (_unknownFields != null)
                    {
                        hash ^= _unknownFields.GetHashCode();
                    }
                    return hash;
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public override string ToString()
                {
                    return pb::JsonFormatter.ToDiagnosticString(this);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public void WriteTo(pb::CodedOutputStream output)
                {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                    output.WriteRawMessage(this);
#else
          if (Type != global::Chorus.WindowsReader.Common.Payload.Types.PayloadMetadata.Types.DeviceType.UnknownDeviceType) {
            output.WriteRawTag(8);
            output.WriteEnum((int) Type);
          }
          if (Version.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Version);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
#endif
                }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
                {
                    if (Type != global::Chorus.WindowsReader.Common.Payload.Types.PayloadMetadata.Types.DeviceType.UnknownDeviceType)
                    {
                        output.WriteRawTag(8);
                        output.WriteEnum((int)Type);
                    }
                    if (Version.Length != 0)
                    {
                        output.WriteRawTag(18);
                        output.WriteString(Version);
                    }
                    if (_unknownFields != null)
                    {
                        _unknownFields.WriteTo(ref output);
                    }
                }
#endif

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public int CalculateSize()
                {
                    int size = 0;
                    if (Type != global::Chorus.WindowsReader.Common.Payload.Types.PayloadMetadata.Types.DeviceType.UnknownDeviceType)
                    {
                        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int)Type);
                    }
                    if (Version.Length != 0)
                    {
                        size += 1 + pb::CodedOutputStream.ComputeStringSize(Version);
                    }
                    if (_unknownFields != null)
                    {
                        size += _unknownFields.CalculateSize();
                    }
                    return size;
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public void MergeFrom(PayloadMetadata other)
                {
                    if (other == null)
                    {
                        return;
                    }
                    if (other.Type != global::Chorus.WindowsReader.Common.Payload.Types.PayloadMetadata.Types.DeviceType.UnknownDeviceType)
                    {
                        Type = other.Type;
                    }
                    if (other.Version.Length != 0)
                    {
                        Version = other.Version;
                    }
                    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public void MergeFrom(pb::CodedInputStream input)
                {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                    input.ReadRawMessage(this);
#else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                Type = (global::Chorus.WindowsReader.Common.Payload.Types.PayloadMetadata.Types.DeviceType) input.ReadEnum();
                break;
              }
              case 18: {
                Version = input.ReadString();
                break;
              }
            }
          }
#endif
                }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
                {
                    uint tag;
                    while ((tag = input.ReadTag()) != 0)
                    {
                        switch (tag)
                        {
                            default:
                                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                                break;
                            case 8:
                                {
                                    Type = (global::Chorus.WindowsReader.Common.Payload.Types.PayloadMetadata.Types.DeviceType)input.ReadEnum();
                                    break;
                                }
                            case 18:
                                {
                                    Version = input.ReadString();
                                    break;
                                }
                        }
                    }
                }
#endif

                #region Nested types
                /// <summary>Container for nested types declared in the PayloadMetadata message type.</summary>
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public static partial class Types
                {
                    /// <summary>
                    /// The type/platform of the device that sent the payload
                    /// </summary>
                    public enum DeviceType
                    {
                        [pbr::OriginalName("UNKNOWN_DEVICE_TYPE")] UnknownDeviceType = 0,
                        [pbr::OriginalName("ANDROID")] Android = 1,
                        [pbr::OriginalName("IOS")] Ios = 2,
                        [pbr::OriginalName("WINDOWS")] Windows = 3,
                    }

                }
                #endregion

            }

        }
        #endregion

    }

    #endregion

}

#endregion Designer generated code
